### ISSUE TITLE
example2.py fails: AttributeError: 'dpctl.tensor._usmarray.usm_ndarray' object has no attribute 'sin'

### ISSUE THREAD

**Issue by jeffhammond** [IntelPython/dpnp#1101]
```
$ python example2.py 
Running on: Intel(R) Iris(R) Xe Graphics [0x9a49]
DPCtrl SYCL queue used
SYCL kernels link time: 5.8e-08 (sec.)
Math backend version: Intel(R) oneAPI Math Kernel Library Version 2022.0-Product Build 20211112 for Intel(R) 64 architecture applications

...Test data type is numpy, each test repetitions 5
type:numpy:N:  2048:Time:5.245e-06:result:-9.589e-01
type:numpy:N:  4096:Time:8.821e-06:result:-9.589e-01
type:numpy:N:  8192:Time:1.931e-05:result:-9.589e-01
type:numpy:N: 16384:Time:3.552e-05:result:-9.589e-01
type:numpy:N: 32768:Time:7.582e-05:result:-9.589e-01
type:numpy:N: 65536:Time:1.481e-04:result:-9.589e-01
...Test data type is dpnp, each test repetitions 5
AttributeError: 'dpctl.tensor._usmarray.usm_ndarray' object has no attribute 'sin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jhammond/example2.py", line 83, in <module>
    result_time, result = run_third_party_function(input_data, test_repetition)
  File "/home/jhammond/example2.py", line 67, in run_third_party_function
    result = common_function_one_input(input)
TypeError: loop of ufunc does not support argument 0 of type dpctl.tensor._usmarray.usm_ndarray which has no callable sin method
```

**Comment by vtavana** [comment]
No issues with dpnp 0.16.0

```
>>> python examples/example2.py 
...Test data type is numpy, each test repetitions 5
type:numpy:N:1048576:Time:9.091e-03:result:-0.9589242746631385
type:numpy:N:2097152:Time:1.577e-02:result:-0.9589242746631385
type:numpy:N:4194304:Time:3.025e-02:result:-0.9589242746631385
type:numpy:N:8388608:Time:6.789e-02:result:-0.9589242746631385
type:numpy:N:16777216:Time:1.223e-01:result:-0.9589242746631385
...Test data type is dpnp, each test repetitions 5
type:dpnp:N:1048576:Time:3.055e-03:result:-0.9589243
type:dpnp:N:2097152:Time:6.793e-03:result:-0.9589243
type:dpnp:N:4194304:Time:9.859e-03:result:-0.9589243
type:dpnp:N:8388608:Time:1.808e-02:result:-0.9589243
type:dpnp:N:16777216:Time:3.288e-02:result:-0.9589243
```
