### ISSUE TITLE
Conda package on `dppy/label/dev` was build with `mkl-dpcpp 2021.3` from oneAPI but requires `mkl-dpcpp 2022.0` 

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpnp#1141]
Reproducer:
```bash
$ conda create -n dpnp dpnp -c dppy/label/dev -c intel --override-channels
...
The following NEW packages will be INSTALLED:
...
  dpctl              dppy/label/dev/linux-64::dpctl-0.12.0dev3-py39h2bc3f7f_36
  dpnp               dppy/label/dev/linux-64::dpnp-0.10.0rc1-py39_2
...
  mkl-dpcpp          intel/linux-64::mkl-dpcpp-2022.0.1-intel_117
...
$ conda activate dpnp
$ python -c "import dpnp"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/localdisk/work/spokhode/miniconda3/envs/dpnp/lib/python3.9/site-packages/dpnp/__init__.py", line 39, in <module>
    from dpnp.dpnp_iface import *
  File "/localdisk/work/spokhode/miniconda3/envs/dpnp/lib/python3.9/site-packages/dpnp/dpnp_iface.py", line 51, in <module>
    from dpnp.dpnp_algo import *
  File "/localdisk/work/spokhode/miniconda3/envs/dpnp/lib/python3.9/site-packages/dpnp/dpnp_algo/__init__.py", line 27, in <module>
    from dpnp.dpnp_algo.dpnp_algo import *
ImportError: libmkl_sycl.so.1: cannot open shared object file: No such file or directory
```
`mkl-dpcpp 2021.3` provides `libmkl_sycl.so.1`.
`mkl-dpcpp 2022.0` provides `libmkl_sycl.so.2`.

**Comment by PokhodenkoSA** [comment]
https://github.com/IntelPython/dpnp/pull/1138 is a solution for this ticket.
