### ISSUE TITLE
Division by scalar raise NotImplementedError

### ISSUE THREAD

**Issue by npolina4** [IntelPython/dpnp#1273]
``` python
import dpnp as xp
a = xp.array([2., 4.])
a/2.
```
``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/localdisk/work/npolina/ws/dpnp/dpnp/dpnp_array.py", line 304, in __truediv__
    return dpnp.true_divide(self, other)
  File "/localdisk/work/npolina/ws/dpnp/dpnp/dpnp_iface_mathematical.py", line 1675, in true_divide
    return dpnp.divide(*args, **kwargs)
  File "/localdisk/work/npolina/ws/dpnp/dpnp/dpnp_iface_mathematical.py", line 585, in divide
    return call_origin(numpy.divide, x1, x2, dtype=dtype, out=out, where=where, **kwargs)
  File "dpnp/dpnp_utils/dpnp_algo_utils.pyx", line 132, in dpnp.dpnp_utils.dpnp_algo_utils.call_origin
    raise NotImplementedError(f"Requested funtion={function.__name__} with args={args} and kwargs={kwargs} "
NotImplementedError: Requested funtion=divide with args=(<dpnp.dpnp_array.dpnp_array object at 0x7f11c51ef9d0>, 2.0) and kwargs={'dtype': None, 'out': None, 'where': True} isn't currently supported and would fall back on NumPy implementation. Define enviroment variable `DPNP_RAISE_EXCEPION_ON_NUMPY_FALLBACK` to `0` if the fall back is required to be supported without rasing an exception.
```

**Comment by npolina4** [comment]
Same problem with subtract and add.

**Comment by antonwolfy** [comment]
@npolina4, the issue was fixed by above PRs and merged.
