### ISSUE TITLE
test_zeros_strides failed with regular testing with exception

### ISSUE THREAD

**Issue by shssf** [IntelPython/dpnp#595]
```
tests/third_party/cupy/creation_tests/test_basic.py::TestBasic::test_zeros_strides Traceback (most recent call last):
  File "dpnp/dpnp_utils/dpnp_algo_utils.pyx", line 117, in dpnp.dpnp_utils.dpnp_algo_utils.checker_throw_type_error
    raise TypeError(f"{ERROR_PREFIX} in function {function_name}() type '{given_type}' is not supported")
TypeError: DPNP error: in function dpnp_dtype_to_DPNPFuncType() type 'd' is not supported
Exception ignored in: 'dpnp.dpnp_algo.dpnp_algo.dpnp_dtype_to_DPNPFuncType'
Traceback (most recent call last):
  File "dpnp/dpnp_utils/dpnp_algo_utils.pyx", line 117, in dpnp.dpnp_utils.dpnp_algo_utils.checker_throw_type_error
    raise TypeError(f"{ERROR_PREFIX} in function {function_name}() type '{given_type}' is not supported")
TypeError: DPNP error: in function dpnp_dtype_to_DPNPFuncType() type 'd' is not supported
terminate called after throwing an instance of 'std::runtime_error'
  what():  DPNP Error: Function ID with unsupported first parameter type.
Fatal Python error: Aborted

```

**Comment by vtavana** [comment]
with dpnp 0.16.0

tests/third_party/cupy/creation_tests/test_basic.py::TestBasic::test_zeros_strides PASSED
