### ISSUE TITLE
test_invalid_order throws an exception

### ISSUE THREAD

**Issue by shssf** [IntelPython/dpnp#597]
```
tests/third_party/cupy/indexing_tests/test_generate.py::TestUnravelIndex::test_invalid_order FAILED
tests/third_party/cupy/indexing_tests/test_generate.py::TestRavelMultiIndex::test_basic Traceback (most recent call last):
  File "dpnp/dpnp_utils/dpnp_algo_utils.pyx", line 117, in dpnp.dpnp_utils.dpnp_algo_utils.checker_throw_type_error
    raise TypeError(f"{ERROR_PREFIX} in function {function_name}() type '{given_type}' is not supported")
TypeError: DPNP error: in function dpnp_dtype_to_DPNPFuncType() type '<class 'numpy.uint8'>' is not supported
Exception ignored in: 'dpnp.dpnp_algo.dpnp_algo.dpnp_dtype_to_DPNPFuncType'
Traceback (most recent call last):
  File "dpnp/dpnp_utils/dpnp_algo_utils.pyx", line 117, in dpnp.dpnp_utils.dpnp_algo_utils.checker_throw_type_error
    raise TypeError(f"{ERROR_PREFIX} in function {function_name}() type '{given_type}' is not supported")
TypeError: DPNP error: in function dpnp_dtype_to_DPNPFuncType() type '<class 'numpy.uint8'>' is not supported
terminate called after throwing an instance of 'std::runtime_error'
  what():  DPNP Error: Function ID with unsupported first parameter type.
Fatal Python error: Aborted

```

**Comment by vtavana** [comment]
With dpnp 0.16.0

tests/third_party/cupy/indexing_tests/test_generate.py::TestUnravelIndex::test_invalid_order PASSED
tests/third_party/cupy/indexing_tests/test_generate.py::TestRavelMultiIndex::test_basic PASSED
